spring:
  servlet:
    multipart:
      max-file-size: -1
  rabbitmq:
      listener:
        simple:
          default-requeue-rejected: false
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATA_SOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
    open-in-view: false
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            action: create
            create-target: create.sql
  mvc:
    static-path-pattern: /static/**
  main:
    banner-mode: off
    allow-circular-references: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: yamuz
    password: RdGakUHndoIPGBBeoKFL
    properties.mail.smtp:
      auth: true
      connectiontimeout: 10000
      timeout: 5000
      writetimeout: 5000
      startssl.enable: false
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
app:
  host: http://localhost:8080
  jwtSecret: jwtToken
  jwtDurationDaysAccess: 1
  jwtDurationDaysRefresh: 60
  fileStorage:
    path: C:\\Users\\Almaz\\Desktop\\Akvelon\\Facebook\\files\\

mail:
  debug: true
  from: yamuz@mail.ru
  transport.protocol: smtp
  smtp:
    auth: true
    starttls.enable: false
    ssl.protocols: TLSv1.2
    ssl.enable: true
    ssl.trust: smtp.mail.ru
springdoc:
  swagger-ui:
    path: /swagger-ui.html

