spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/facebook
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
