spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATA_SOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
  mvc:
    static-path-pattern: /static/**