<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FILES PAGE</title>
</head>
<body>

<div>
<img src="/api/file/5770ee4f-5d19-4b92-9d98-eee8619982a3" width="200px">
</div>

</body>
</html>